src/Bill.Demo.Solutions/Bill.Demo.Web/Models/ErrorViewModel.cs
using System;

namespace Bill.Demo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Bill.Demo.Solutions/Bill.Demo.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bill.Demo.IModuleServices.Users;
using Bill.Demo.IModuleServices.Users.Dto;
using Microsoft.AspNetCore.Mvc;
using Surging.Core.CPlatform.Utilities;
using Surging.Core.ProxyGenerator;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Bill.Demo.Web.Controllers
{
    public class AuthController : Controller
    {
        // GET: /<controller>/
        public async Task<IActionResult> User()
        {
            return View();
        }

        public async Task<JsonResult> GetAllUsers()
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");

            var output = await userProxy.GetAllUsers();

            return new JsonResult(output);
        }

        public async Task<JsonResult> Add(UserDto dto)
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");
            var output = await userProxy.CreateUser(new IModuleServices.Users.Dto.CreateUserDto
            {
                EmailAddress = dto.EmailAddress,
                Name = dto.Name,
                FullName = dto.FullName,
                Password = dto.Password,
                PhoneNumber = dto.PhoneNumber,
                Surname = dto.Surname,
            });
            return new JsonResult(output);
        }
        
        public async Task<IActionResult> Delete(Int64 id)
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");
            await userProxy.DeleteUser(id);

            return RedirectToAction("User");
        }

        public async Task<JsonResult> GetUser(Int64 id)
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");
            var output= await userProxy.GetUserById(id);

            return new JsonResult(output);
        }
        public async Task<JsonResult> Update(UserDto dto)
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");
            var output = await userProxy.UpdateUser(dto);
            return new JsonResult(output);
        }
    }

}

src/Bill.Demo.Solutions/Bill.Demo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bill.Demo.Web.Models;
using Surging.Core.CPlatform.Utilities;
using Surging.Core.ProxyGenerator;
using Bill.Demo.IModuleServices.Users;
using Bill.Demo.IModuleServices.Users.Events;

namespace Bill.Demo.Web.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");

            var userName = await userProxy.GetUserName(1);
            ViewBag.UserName = userName;
            //ViewBag.UserName = "test";
            return View();
        }
        public async Task<JsonResult> TestLoop10000()
        {
            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            var userProxy = service.CreateProxy<IUserService>("User");

            //1w次调用
            var watch = Stopwatch.StartNew();
            for (var i = 0; i < 10000; i++)
            {
                var a = await userProxy.GetDictionary();
                //var result = serviceProxyProvider.Invoke<object>(new Dictionary<string, object>(), "api/user/GetDictionary", "User").Result;
            }
            watch.Stop();

            var watchMessage = $"1w次调用结束，执行时间：{watch.ElapsedMilliseconds}ms";

            return new JsonResult(watchMessage);
        }

        public JsonResult TestRabbitMq(){

            var service = ServiceLocator.GetService<IServiceProxyFactory>();
            service.CreateProxy<IUserService>("User").PublishThroughEventBusAsync(new UserEvent{
                UserId="1",
                Name="Bill",
                Age="18"
            });

            return new JsonResult("发布User事件成功");
        }

        
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Bill.Demo.Solutions/Bill.Demo.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Bill.Demo.Solutions/Bill.Demo.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Bill.Demo.Solutions/Bill.Demo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<p>
    <b>UserName:</b><br />
    @ViewBag.UserName
</p>

<div>
    <button id="btnTestLoop10000">测试循环 1w 次调用</button>
    <p id="content"></p>
</div>

<div>
    <button id="btnRabbitMq">发布User事件</button>
    <p id="mqContent"></p>
</div>

@*<script src="~/js/jquery.js"></script>*@

@section Scripts{
    <script type="text/javascript">
        $(function ($) {
            $("#btnTestLoop10000").click(function () {
                $.ajax({
                    type: "GET",
                    url: '@Url.Content("~/home/TestLoop10000")',
                    success: function (msg) {
                        $("#content").append(msg +"<br />");
                    }
                });
            });

            $('#btnRabbitMq').click(function(){
                $.ajax({
                    type: "GET",
                    url: '@Url.Content("~/home/TestRabbitMq")',
                    success: function (msg) {
                        $("#mqContent").append(msg +"<br />");
                    }
                });
            });
        

        });
    </script>
    }

src/Bill.Demo.Solutions/Bill.Demo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bill.Demo.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Bill.Demo.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Auth" asp-action="User">User</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Bill.Demo.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>